-- =====================================================
-- Migration: AI Program Generation Tables
-- =====================================================
-- Tables for storing AI-generated workout programs
-- Built for use with Anthropic Claude API
--
-- Run this in Supabase SQL Editor AFTER 001_create_client_profiles.sql

-- =====================================================
-- ENUM TYPES
-- =====================================================

DO $$ BEGIN
  CREATE TYPE program_status AS ENUM (
    'draft',
    'active',
    'paused',
    'completed',
    'archived'
  );
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- =====================================================
-- TABLE 1: ai_programs (Master Program Record)
-- =====================================================

CREATE TABLE IF NOT EXISTS ai_programs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Links
  client_profile_id UUID REFERENCES client_profiles(id) ON DELETE CASCADE,
  trainer_id UUID NOT NULL,  -- Who created/owns this program
  studio_id UUID,  -- Multi-tenancy

  -- Program Metadata
  program_name TEXT NOT NULL,
  description TEXT,
  status program_status DEFAULT 'draft',

  -- Program Structure
  total_weeks INT NOT NULL CHECK (total_weeks > 0 AND total_weeks <= 52),
  sessions_per_week INT NOT NULL CHECK (sessions_per_week >= 1 AND sessions_per_week <= 7),
  session_duration_minutes INT CHECK (session_duration_minutes > 0),

  -- Goal Configuration (from client profile)
  primary_goal TEXT NOT NULL,
  secondary_goals TEXT[] DEFAULT '{}',
  experience_level TEXT NOT NULL,

  -- Program Dates
  start_date DATE,
  end_date DATE,
  actual_completion_date DATE,

  -- AI Generation Metadata
  ai_model TEXT DEFAULT 'claude-3-5-sonnet-20241022',  -- Anthropic model used
  generation_prompt_version TEXT,  -- Track prompt versions
  generation_parameters JSONB,  -- Store generation config
  generated_at TIMESTAMPTZ,

  -- Program Summary (generated by AI)
  ai_rationale TEXT,  -- Why this program was designed this way
  movement_balance_summary JSONB,  -- {push: 6, pull: 6, squat: 4, hinge: 4, ...}
  weekly_structure_summary TEXT,  -- Human-readable summary

  -- Progress Tracking
  completion_percentage NUMERIC(5, 2) DEFAULT 0.00,
  sessions_completed INT DEFAULT 0,
  sessions_total INT,

  -- Flags
  is_template BOOLEAN DEFAULT false,  -- Can be reused for other clients
  is_published BOOLEAN DEFAULT false,  -- Visible to client
  allow_client_modifications BOOLEAN DEFAULT false,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID,  -- auth.uid()

  -- Constraints
  CONSTRAINT valid_date_range CHECK (end_date IS NULL OR end_date >= start_date)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_ai_programs_client ON ai_programs(client_profile_id);
CREATE INDEX IF NOT EXISTS idx_ai_programs_trainer ON ai_programs(trainer_id);
CREATE INDEX IF NOT EXISTS idx_ai_programs_studio ON ai_programs(studio_id);
CREATE INDEX IF NOT EXISTS idx_ai_programs_status ON ai_programs(status);
CREATE INDEX IF NOT EXISTS idx_ai_programs_dates ON ai_programs(start_date, end_date);

-- =====================================================
-- TABLE 2: ai_workouts (Individual Workout Sessions)
-- =====================================================

CREATE TABLE IF NOT EXISTS ai_workouts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Link to program
  program_id UUID NOT NULL REFERENCES ai_programs(id) ON DELETE CASCADE,

  -- Workout Position
  week_number INT NOT NULL CHECK (week_number > 0),
  day_number INT NOT NULL CHECK (day_number >= 1 AND day_number <= 7),
  session_order INT,  -- Order within the week (1st, 2nd, 3rd session)

  -- Workout Metadata
  workout_name TEXT NOT NULL,  -- e.g., "Push Day A", "Full Body 1"
  workout_focus TEXT,  -- e.g., "Upper Body Push + Core"
  session_type TEXT,  -- e.g., "strength", "hypertrophy", "conditioning", "mobility"

  -- Scheduling
  scheduled_date DATE,
  planned_duration_minutes INT,

  -- Movement Balance (for this session)
  movement_patterns_covered TEXT[],  -- ['push_horizontal', 'squat', 'core']
  planes_of_motion_covered TEXT[],  -- ['sagittal', 'frontal']
  primary_muscle_groups TEXT[],  -- ['chest', 'legs', 'core']

  -- AI Generation
  ai_rationale TEXT,  -- Why these exercises were chosen
  exercise_selection_criteria JSONB,  -- What filters were applied

  -- Session Completion Tracking
  is_completed BOOLEAN DEFAULT false,
  completed_at TIMESTAMPTZ,
  actual_duration_minutes INT,
  overall_rpe NUMERIC(3, 1),  -- 1-10 scale
  trainer_notes TEXT,
  client_feedback TEXT,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Unique constraint: one workout per program/week/day
  UNIQUE(program_id, week_number, day_number)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_ai_workouts_program ON ai_workouts(program_id);
CREATE INDEX IF NOT EXISTS idx_ai_workouts_week_day ON ai_workouts(week_number, day_number);
CREATE INDEX IF NOT EXISTS idx_ai_workouts_scheduled ON ai_workouts(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_ai_workouts_completed ON ai_workouts(is_completed);

-- =====================================================
-- TABLE 3: ai_workout_exercises (Exercises in Workouts)
-- =====================================================

CREATE TABLE IF NOT EXISTS ai_workout_exercises (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Links
  workout_id UUID NOT NULL REFERENCES ai_workouts(id) ON DELETE CASCADE,
  exercise_id UUID NOT NULL REFERENCES ta_exercise_library_original(id) ON DELETE RESTRICT,

  -- Exercise Position
  exercise_order INT NOT NULL,  -- Order in workout (1, 2, 3, ...)
  block_label TEXT,  -- e.g., "A1", "A2", "B1" for supersets/circuits

  -- Prescription (Target Values)
  sets INT CHECK (sets > 0),
  reps_min INT,
  reps_max INT,
  reps_target TEXT,  -- Can be range "8-12" or "AMRAP" or "EMOM:12"
  target_load_kg NUMERIC(6, 2),
  target_load_percentage NUMERIC(5, 2),  -- % of 1RM
  target_rpe NUMERIC(3, 1),  -- Rate of Perceived Exertion (1-10)
  target_rir INT,  -- Reps in Reserve (0-5)

  -- Tempo & Rest
  tempo TEXT,  -- e.g., "3-1-1-0" (eccentric-pause-concentric-pause)
  rest_seconds INT,

  -- Time-Based (for cardio, planks, holds)
  target_duration_seconds INT,
  target_distance_meters INT,

  -- Exercise Type Specifics
  is_unilateral BOOLEAN DEFAULT false,
  is_bodyweight BOOLEAN DEFAULT false,
  is_timed BOOLEAN DEFAULT false,

  -- Coaching Cues (AI-generated or from database)
  coaching_cues TEXT[],
  common_mistakes TEXT[],
  modifications TEXT[],

  -- Actual Performance (Logged During Session)
  actual_sets INT,
  actual_reps INT,
  actual_load_kg NUMERIC(6, 2),
  actual_rpe NUMERIC(3, 1),
  actual_duration_seconds INT,
  actual_distance_meters INT,
  performance_notes TEXT,

  -- Completion Tracking
  is_completed BOOLEAN DEFAULT false,
  skipped BOOLEAN DEFAULT false,
  skip_reason TEXT,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_ai_workout_ex_workout ON ai_workout_exercises(workout_id);
CREATE INDEX IF NOT EXISTS idx_ai_workout_ex_exercise ON ai_workout_exercises(exercise_id);
CREATE INDEX IF NOT EXISTS idx_ai_workout_ex_order ON ai_workout_exercises(workout_id, exercise_order);
CREATE INDEX IF NOT EXISTS idx_ai_workout_ex_block ON ai_workout_exercises(workout_id, block_label);

-- =====================================================
-- TABLE 4: ai_nutrition_plans (Optional Nutrition Guidance)
-- =====================================================

CREATE TABLE IF NOT EXISTS ai_nutrition_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Link to program (1:1 relationship)
  program_id UUID UNIQUE NOT NULL REFERENCES ai_programs(id) ON DELETE CASCADE,

  -- Calorie & Macro Targets
  daily_calories INT,
  protein_grams INT,
  carbs_grams INT,
  fats_grams INT,
  fiber_grams INT,

  -- Calculation Method
  calculation_method TEXT,  -- e.g., "Mifflin-St Jeor + Harris-Benedict"
  tdee_estimated INT,  -- Total Daily Energy Expenditure
  calorie_adjustment_percentage NUMERIC(5, 2),  -- +20% surplus or -20% deficit

  -- Meal Structure
  meals_per_day INT,
  meal_timing_notes TEXT,
  pre_workout_nutrition TEXT,
  post_workout_nutrition TEXT,

  -- Sample Meals (AI-generated suggestions)
  meal_templates JSONB,  -- [{meal: 'Breakfast', ideas: ['Oatmeal + protein shake', ...]}, ...]

  -- Hydration & Supplements
  daily_water_liters NUMERIC(4, 2),
  supplement_recommendations TEXT[],

  -- Dietary Considerations (from client profile)
  dietary_restrictions TEXT[],
  dietary_preferences TEXT[],

  -- AI Generation
  ai_rationale TEXT,
  generated_at TIMESTAMPTZ,

  -- Disclaimer
  disclaimer TEXT DEFAULT 'This is general nutrition guidance. Consult a registered dietitian or physician for personalized medical nutrition advice.',

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index
CREATE INDEX IF NOT EXISTS idx_ai_nutrition_program ON ai_nutrition_plans(program_id);

-- =====================================================
-- TABLE 5: ai_generations (AI Call Logging)
-- =====================================================

CREATE TABLE IF NOT EXISTS ai_generations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Scope (what was generated)
  generation_type TEXT NOT NULL,  -- 'program', 'workout', 'exercise_block', 'nutrition', 'progression'
  entity_id UUID,  -- program_id, workout_id, etc.
  entity_type TEXT,  -- 'ai_programs', 'ai_workouts', etc.

  -- AI Model Info
  ai_provider TEXT DEFAULT 'anthropic',  -- 'anthropic', 'openai', etc.
  ai_model TEXT NOT NULL,  -- 'claude-3-5-sonnet-20241022'
  prompt_version TEXT,

  -- Request/Response
  system_prompt TEXT,
  user_prompt TEXT,
  prompt_parameters JSONB,  -- Input parameters
  ai_response TEXT,  -- Full AI response
  structured_output JSONB,  -- Parsed JSON output

  -- Token Usage
  input_tokens INT,
  output_tokens INT,
  total_tokens INT,
  estimated_cost_usd NUMERIC(10, 6),

  -- Tool Calls (if using function calling)
  tool_calls JSONB,
  tool_results JSONB,

  -- Performance
  latency_ms INT,  -- Time taken for API call
  retry_count INT DEFAULT 0,

  -- Status
  status TEXT DEFAULT 'success',  -- 'success', 'error', 'partial'
  error_message TEXT,
  error_code TEXT,

  -- Context
  created_by UUID,  -- auth.uid()
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_ai_gen_type ON ai_generations(generation_type);
CREATE INDEX IF NOT EXISTS idx_ai_gen_entity ON ai_generations(entity_id, entity_type);
CREATE INDEX IF NOT EXISTS idx_ai_gen_created ON ai_generations(created_at);
CREATE INDEX IF NOT EXISTS idx_ai_gen_model ON ai_generations(ai_model);
CREATE INDEX IF NOT EXISTS idx_ai_gen_status ON ai_generations(status);

-- =====================================================
-- TABLE 6: ai_program_revisions (Version History)
-- =====================================================

CREATE TABLE IF NOT EXISTS ai_program_revisions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Link to program
  program_id UUID NOT NULL REFERENCES ai_programs(id) ON DELETE CASCADE,

  -- Version Info
  revision_number INT NOT NULL,
  revision_type TEXT,  -- 'initial', 'edit', 'progression', 'regeneration'
  change_description TEXT,

  -- Snapshot (full program state at this revision)
  program_snapshot JSONB NOT NULL,  -- Complete program + workouts + exercises as JSON
  workouts_count INT,
  exercises_count INT,

  -- What Changed (optional, for tracking)
  changes_made JSONB,  -- {added: [], removed: [], modified: []}

  -- Metadata
  created_by UUID,  -- Who made this revision
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- Unique constraint: version numbers must be sequential
  UNIQUE(program_id, revision_number)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_ai_rev_program ON ai_program_revisions(program_id);
CREATE INDEX IF NOT EXISTS idx_ai_rev_number ON ai_program_revisions(program_id, revision_number DESC);
CREATE INDEX IF NOT EXISTS idx_ai_rev_created ON ai_program_revisions(created_at);

-- =====================================================
-- TRIGGERS (Auto-update timestamps)
-- =====================================================

-- ai_programs updated_at trigger
CREATE TRIGGER update_ai_programs_updated_at
  BEFORE UPDATE ON ai_programs
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ai_workouts updated_at trigger
CREATE TRIGGER update_ai_workouts_updated_at
  BEFORE UPDATE ON ai_workouts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ai_workout_exercises updated_at trigger
CREATE TRIGGER update_ai_workout_exercises_updated_at
  BEFORE UPDATE ON ai_workout_exercises
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ai_nutrition_plans updated_at trigger
CREATE TRIGGER update_ai_nutrition_plans_updated_at
  BEFORE UPDATE ON ai_nutrition_plans
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE ai_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_workouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_workout_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_nutrition_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_generations ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_program_revisions ENABLE ROW LEVEL SECURITY;

-- ai_programs policies
CREATE POLICY "Trainers can view their programs"
  ON ai_programs FOR SELECT
  USING (auth.uid() = trainer_id OR auth.uid() = created_by);

CREATE POLICY "Trainers can create programs"
  ON ai_programs FOR INSERT
  WITH CHECK (auth.uid() = created_by);

CREATE POLICY "Trainers can update their programs"
  ON ai_programs FOR UPDATE
  USING (auth.uid() = trainer_id OR auth.uid() = created_by);

CREATE POLICY "Trainers can delete their programs"
  ON ai_programs FOR DELETE
  USING (auth.uid() = created_by);

-- ai_workouts policies (inherit from program)
CREATE POLICY "Trainers can view workouts from their programs"
  ON ai_workouts FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM ai_programs
    WHERE ai_programs.id = ai_workouts.program_id
    AND (ai_programs.trainer_id = auth.uid() OR ai_programs.created_by = auth.uid())
  ));

CREATE POLICY "Trainers can insert workouts into their programs"
  ON ai_workouts FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM ai_programs
    WHERE ai_programs.id = ai_workouts.program_id
    AND (ai_programs.trainer_id = auth.uid() OR ai_programs.created_by = auth.uid())
  ));

CREATE POLICY "Trainers can update workouts in their programs"
  ON ai_workouts FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM ai_programs
    WHERE ai_programs.id = ai_workouts.program_id
    AND (ai_programs.trainer_id = auth.uid() OR ai_programs.created_by = auth.uid())
  ));

CREATE POLICY "Trainers can delete workouts from their programs"
  ON ai_workouts FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM ai_programs
    WHERE ai_programs.id = ai_workouts.program_id
    AND (ai_programs.trainer_id = auth.uid() OR ai_programs.created_by = auth.uid())
  ));

-- ai_workout_exercises policies (inherit from workout → program)
CREATE POLICY "Trainers can view exercises from their workouts"
  ON ai_workout_exercises FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM ai_workouts
    JOIN ai_programs ON ai_programs.id = ai_workouts.program_id
    WHERE ai_workouts.id = ai_workout_exercises.workout_id
    AND (ai_programs.trainer_id = auth.uid() OR ai_programs.created_by = auth.uid())
  ));

CREATE POLICY "Trainers can insert exercises into their workouts"
  ON ai_workout_exercises FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM ai_workouts
    JOIN ai_programs ON ai_programs.id = ai_workouts.program_id
    WHERE ai_workouts.id = ai_workout_exercises.workout_id
    AND (ai_programs.trainer_id = auth.uid() OR ai_programs.created_by = auth.uid())
  ));

CREATE POLICY "Trainers can update exercises in their workouts"
  ON ai_workout_exercises FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM ai_workouts
    JOIN ai_programs ON ai_programs.id = ai_workouts.program_id
    WHERE ai_workouts.id = ai_workout_exercises.workout_id
    AND (ai_programs.trainer_id = auth.uid() OR ai_programs.created_by = auth.uid())
  ));

CREATE POLICY "Trainers can delete exercises from their workouts"
  ON ai_workout_exercises FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM ai_workouts
    JOIN ai_programs ON ai_programs.id = ai_workouts.program_id
    WHERE ai_workouts.id = ai_workout_exercises.workout_id
    AND (ai_programs.trainer_id = auth.uid() OR ai_programs.created_by = auth.uid())
  ));

-- ai_nutrition_plans policies
CREATE POLICY "Trainers can view nutrition plans for their programs"
  ON ai_nutrition_plans FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM ai_programs
    WHERE ai_programs.id = ai_nutrition_plans.program_id
    AND (ai_programs.trainer_id = auth.uid() OR ai_programs.created_by = auth.uid())
  ));

CREATE POLICY "Trainers can create nutrition plans"
  ON ai_nutrition_plans FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM ai_programs
    WHERE ai_programs.id = ai_nutrition_plans.program_id
    AND (ai_programs.trainer_id = auth.uid() OR ai_programs.created_by = auth.uid())
  ));

CREATE POLICY "Trainers can update nutrition plans"
  ON ai_nutrition_plans FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM ai_programs
    WHERE ai_programs.id = ai_nutrition_plans.program_id
    AND (ai_programs.trainer_id = auth.uid() OR ai_programs.created_by = auth.uid())
  ));

CREATE POLICY "Trainers can delete nutrition plans"
  ON ai_nutrition_plans FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM ai_programs
    WHERE ai_programs.id = ai_nutrition_plans.program_id
    AND (ai_programs.trainer_id = auth.uid() OR ai_programs.created_by = auth.uid())
  ));

-- ai_generations policies
CREATE POLICY "Users can view their AI generations"
  ON ai_generations FOR SELECT
  USING (auth.uid() = created_by);

CREATE POLICY "Users can create AI generation logs"
  ON ai_generations FOR INSERT
  WITH CHECK (auth.uid() = created_by);

-- ai_program_revisions policies
CREATE POLICY "Trainers can view revisions of their programs"
  ON ai_program_revisions FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM ai_programs
    WHERE ai_programs.id = ai_program_revisions.program_id
    AND (ai_programs.trainer_id = auth.uid() OR ai_programs.created_by = auth.uid())
  ));

CREATE POLICY "Trainers can create revisions"
  ON ai_program_revisions FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM ai_programs
    WHERE ai_programs.id = ai_program_revisions.program_id
    AND (ai_programs.trainer_id = auth.uid() OR ai_programs.created_by = auth.uid())
  ));

-- =====================================================
-- HELPER FUNCTIONS
-- =====================================================

-- Function to automatically create first revision when program is created
CREATE OR REPLACE FUNCTION create_initial_program_revision()
RETURNS TRIGGER AS $$
BEGIN
  -- Create revision 1 with initial program state
  INSERT INTO ai_program_revisions (
    program_id,
    revision_number,
    revision_type,
    change_description,
    program_snapshot,
    workouts_count,
    exercises_count,
    created_by
  ) VALUES (
    NEW.id,
    1,
    'initial',
    'Initial program creation',
    jsonb_build_object(
      'program', to_jsonb(NEW),
      'workouts', '[]'::jsonb,
      'exercises', '[]'::jsonb
    ),
    0,
    0,
    NEW.created_by
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to create initial revision
CREATE TRIGGER create_program_initial_revision
  AFTER INSERT ON ai_programs
  FOR EACH ROW
  EXECUTE FUNCTION create_initial_program_revision();

-- =====================================================
-- VERIFICATION QUERY
-- =====================================================

SELECT
  'AI Program tables created successfully' AS status,
  (SELECT COUNT(*) FROM ai_programs) AS programs_count,
  (SELECT COUNT(*) FROM ai_workouts) AS workouts_count,
  (SELECT COUNT(*) FROM ai_workout_exercises) AS exercises_count,
  (SELECT COUNT(*) FROM ai_generations) AS generations_count;
-- Add generation status tracking to ai_programs table
-- This allows background job processing for AI program generation

-- Add generation_status column
ALTER TABLE ai_programs
ADD COLUMN IF NOT EXISTS generation_status TEXT DEFAULT 'completed'
CHECK (generation_status IN ('generating', 'completed', 'failed'));

-- Add generation_error column for error messages
ALTER TABLE ai_programs
ADD COLUMN IF NOT EXISTS generation_error TEXT;

-- Create index for querying by status
CREATE INDEX IF NOT EXISTS idx_ai_programs_generation_status
ON ai_programs(generation_status)
WHERE generation_status != 'completed';

-- Add comment explaining the status field
COMMENT ON COLUMN ai_programs.generation_status IS
'Status of AI program generation: generating (in progress), completed (success), failed (error occurred)';

COMMENT ON COLUMN ai_programs.generation_error IS
'Error message if generation failed, null otherwise';
-- Add progress tracking fields to ai_programs table
-- This enables real-time progress updates during AI generation

ALTER TABLE ai_programs
ADD COLUMN IF NOT EXISTS progress_message TEXT;

ALTER TABLE ai_programs
ADD COLUMN IF NOT EXISTS current_step INTEGER DEFAULT 0;

ALTER TABLE ai_programs
ADD COLUMN IF NOT EXISTS total_steps INTEGER DEFAULT 0;

ALTER TABLE ai_programs
ADD COLUMN IF NOT EXISTS progress_percentage INTEGER DEFAULT 0
CHECK (progress_percentage >= 0 AND progress_percentage <= 100);

-- Create index for querying in-progress generations
CREATE INDEX IF NOT EXISTS idx_ai_programs_progress
ON ai_programs(generation_status, progress_percentage)
WHERE generation_status = 'generating';

-- Add comment for documentation
COMMENT ON COLUMN ai_programs.progress_message IS 'Human-readable description of current generation step (e.g., "Generating week 1 (chunk 1/8)...")';
COMMENT ON COLUMN ai_programs.current_step IS 'Current step number in the generation process';
COMMENT ON COLUMN ai_programs.total_steps IS 'Total number of steps in the generation process';
COMMENT ON COLUMN ai_programs.progress_percentage IS 'Completion percentage from 0 to 100';
