import { Exercise } from '@/lib/types';
import generatedExercises from '@/data/generated-exercises.json';

// Import all 873 exercises from Supabase storage
// Generated by scripts/import-exercises-from-list.ts
// Convert null values to undefined for TypeScript compatibility
export const MOCK_EXERCISES: Exercise[] = generatedExercises.map((ex: any) => ({
  ...ex,
  startImageUrl: ex.startImageUrl ?? undefined,
  endImageUrl: ex.endImageUrl ?? undefined,
  primaryMuscles: ex.primaryMuscles ?? undefined,
  secondaryMuscles: ex.secondaryMuscles ?? undefined,
  equipment: ex.equipment ?? undefined,
  modifications: ex.modifications ?? undefined,
  commonMistakes: ex.commonMistakes ?? undefined,
}));

// Helper functions
export function getExerciseById(id: string): Exercise | undefined {
  return MOCK_EXERCISES.find((ex) => ex.id === id);
}

export function getExercisesByCategory(category: string): Exercise[] {
  return MOCK_EXERCISES.filter((ex) => ex.category === category);
}

export function searchExercises(query: string): Exercise[] {
  const lowerQuery = query.toLowerCase();
  return MOCK_EXERCISES.filter(
    (ex) =>
      ex.name.toLowerCase().includes(lowerQuery) ||
      ex.category.toLowerCase().includes(lowerQuery) ||
      ex.equipment?.toLowerCase().includes(lowerQuery)
  );
}

export function getExercisesByEquipment(equipment: string): Exercise[] {
  return MOCK_EXERCISES.filter((ex) => ex.equipment === equipment);
}

export function getAllCategories(): string[] {
  return Array.from(new Set(MOCK_EXERCISES.map((ex) => ex.category)));
}

export function getAllEquipment(): string[] {
  return Array.from(
    new Set(
      MOCK_EXERCISES.map((ex) => ex.equipment).filter(
        (eq): eq is string => eq !== undefined
      )
    )
  ).sort();
}
