import { WorkoutTemplate } from '@/lib/types';

export const MOCK_TEMPLATES: WorkoutTemplate[] = [
  // ========================================
  // STANDARD 3-BLOCK TEMPLATE
  // ========================================
  {
    id: 'template_results_first',
    name: '=Results First Session',
    description: 'Go-to workout for new clients. Balanced full-body routine.',
    type: 'standard',
    createdBy: 'user_owner_1',
    assignedStudios: ['studio_1', 'studio_2', 'studio_3'],
    blocks: [
      {
        id: 'block_1',
        blockNumber: 1,
        name: 'Block 1',
        exercises: [
          {
            id: 'te_1_1',
            exerciseId: 'ex_cardio_treadmill',
            position: 1,
            muscleGroup: 'cardio',
            resistanceType: 'bodyweight',
            resistanceValue: 0,
            repsMin: 0,
            repsMax: 0,
            sets: 1,
            cardioDuration: 180, // 3 minutes
            cardioIntensity: 7,
          },
          {
            id: 'te_1_2',
            exerciseId: 'ex_chest_db_press',
            position: 2,
            muscleGroup: 'chest',
            resistanceType: 'weight',
            resistanceValue: 25,
            repsMin: 10,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_1_3',
            exerciseId: 'ex_back_bent_row',
            position: 3,
            muscleGroup: 'back',
            resistanceType: 'weight',
            resistanceValue: 20,
            repsMin: 10,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_1_4',
            exerciseId: 'ex_legs_goblet_squat',
            position: 4,
            muscleGroup: 'legs',
            resistanceType: 'weight',
            resistanceValue: 20,
            repsMin: 10,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_1_5',
            exerciseId: 'ex_core_plank',
            position: 5,
            muscleGroup: 'core',
            resistanceType: 'bodyweight',
            resistanceValue: 0,
            repsMin: 0,
            repsMax: 0,
            sets: 2,
            cardioDuration: 30,
            cardioIntensity: 5,
          },
        ],
      },
      {
        id: 'block_2',
        blockNumber: 2,
        name: 'Block 2',
        exercises: [
          {
            id: 'te_2_1',
            exerciseId: 'ex_cardio_bike',
            position: 1,
            muscleGroup: 'cardio',
            resistanceType: 'bodyweight',
            resistanceValue: 0,
            repsMin: 0,
            repsMax: 0,
            sets: 1,
            cardioDuration: 180,
            cardioIntensity: 6,
          },
          {
            id: 'te_2_2',
            exerciseId: 'ex_chest_pushup',
            position: 2,
            muscleGroup: 'chest',
            resistanceType: 'bodyweight',
            resistanceValue: 0,
            repsMin: 10,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_2_3',
            exerciseId: 'ex_back_lat_pulldown',
            position: 3,
            muscleGroup: 'back',
            resistanceType: 'weight',
            resistanceValue: 30,
            repsMin: 10,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_2_4',
            exerciseId: 'ex_legs_lunges',
            position: 4,
            muscleGroup: 'legs',
            resistanceType: 'weight',
            resistanceValue: 15,
            repsMin: 10,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_2_5',
            exerciseId: 'ex_core_russian_twist',
            position: 5,
            muscleGroup: 'core',
            resistanceType: 'weight',
            resistanceValue: 10,
            repsMin: 10,
            repsMax: 15,
            sets: 2,
          },
        ],
      },
      {
        id: 'block_3',
        blockNumber: 3,
        name: 'Block 3',
        exercises: [
          {
            id: 'te_3_1',
            exerciseId: 'ex_cardio_rower',
            position: 1,
            muscleGroup: 'cardio',
            resistanceType: 'bodyweight',
            resistanceValue: 0,
            repsMin: 0,
            repsMax: 0,
            sets: 1,
            cardioDuration: 180,
            cardioIntensity: 8,
          },
          {
            id: 'te_3_2',
            exerciseId: 'ex_shoulders_db_press',
            position: 2,
            muscleGroup: 'shoulders',
            resistanceType: 'weight',
            resistanceValue: 15,
            repsMin: 10,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_3_3',
            exerciseId: 'ex_biceps_curl',
            position: 3,
            muscleGroup: 'biceps',
            resistanceType: 'weight',
            resistanceValue: 12,
            repsMin: 10,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_3_4',
            exerciseId: 'ex_triceps_extension',
            position: 4,
            muscleGroup: 'triceps',
            resistanceType: 'weight',
            resistanceValue: 10,
            repsMin: 10,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_3_5',
            exerciseId: 'ex_stretch_hamstring',
            position: 5,
            muscleGroup: 'stretch',
            resistanceType: 'bodyweight',
            resistanceValue: 0,
            repsMin: 0,
            repsMax: 0,
            sets: 1,
            cardioDuration: 30,
            cardioIntensity: 2,
          },
        ],
      },
    ],
    createdAt: '2025-10-01T10:00:00Z',
    updatedAt: '2025-10-15T14:30:00Z',
  },

  // ========================================
  // RESISTANCE-ONLY TEMPLATE (NO CARDIO)
  // ========================================
  {
    id: 'template_resistance_only',
    name: 'Resistance Only Power Hour',
    description: 'Pure strength training - no cardio, all resistance.',
    type: 'resistance_only',
    createdBy: 'user_owner_1',
    assignedStudios: ['studio_1'],
    blocks: [
      {
        id: 'block_r1',
        blockNumber: 1,
        name: 'Upper Body Focus',
        exercises: [
          {
            id: 'te_r1_1',
            exerciseId: 'ex_chest_db_press',
            position: 1,
            muscleGroup: 'chest',
            resistanceType: 'weight',
            resistanceValue: 30,
            repsMin: 8,
            repsMax: 12,
            sets: 3,
          },
          {
            id: 'te_r1_2',
            exerciseId: 'ex_back_bent_row',
            position: 2,
            muscleGroup: 'back',
            resistanceType: 'weight',
            resistanceValue: 25,
            repsMin: 8,
            repsMax: 12,
            sets: 3,
          },
          {
            id: 'te_r1_3',
            exerciseId: 'ex_shoulders_db_press',
            position: 3,
            muscleGroup: 'shoulders',
            resistanceType: 'weight',
            resistanceValue: 20,
            repsMin: 8,
            repsMax: 12,
            sets: 3,
          },
        ],
      },
      {
        id: 'block_r2',
        blockNumber: 2,
        name: 'Lower Body Focus',
        exercises: [
          {
            id: 'te_r2_1',
            exerciseId: 'ex_legs_goblet_squat',
            position: 1,
            muscleGroup: 'legs',
            resistanceType: 'weight',
            resistanceValue: 30,
            repsMin: 8,
            repsMax: 12,
            sets: 3,
          },
          {
            id: 'te_r2_2',
            exerciseId: 'ex_legs_lunges',
            position: 2,
            muscleGroup: 'legs',
            resistanceType: 'weight',
            resistanceValue: 20,
            repsMin: 8,
            repsMax: 12,
            sets: 3,
          },
          {
            id: 'te_r2_3',
            exerciseId: 'ex_core_plank',
            position: 3,
            muscleGroup: 'core',
            resistanceType: 'bodyweight',
            resistanceValue: 0,
            repsMin: 0,
            repsMax: 0,
            sets: 3,
            cardioDuration: 45,
            cardioIntensity: 6,
          },
        ],
      },
    ],
    createdAt: '2025-10-10T09:00:00Z',
    updatedAt: '2025-10-18T16:00:00Z',
  },

  // ========================================
  // ADVANCED HIIT TEMPLATE
  // ========================================
  {
    id: 'template_advanced_hiit',
    name: 'Advanced HIIT Blast',
    description: 'High-intensity interval training for experienced clients.',
    type: 'standard',
    createdBy: 'user_owner_1',
    assignedStudios: ['studio_1', 'studio_2'],
    blocks: [
      {
        id: 'block_h1',
        blockNumber: 1,
        name: 'Block 1 - Explosive',
        exercises: [
          {
            id: 'te_h1_1',
            exerciseId: 'ex_cardio_burpees',
            position: 1,
            muscleGroup: 'cardio',
            resistanceType: 'bodyweight',
            resistanceValue: 0,
            repsMin: 0,
            repsMax: 0,
            sets: 1,
            cardioDuration: 120,
            cardioIntensity: 9,
          },
          {
            id: 'te_h1_2',
            exerciseId: 'ex_chest_pushup',
            position: 2,
            muscleGroup: 'chest',
            resistanceType: 'bodyweight',
            resistanceValue: 0,
            repsMin: 15,
            repsMax: 20,
            sets: 2,
          },
          {
            id: 'te_h1_3',
            exerciseId: 'ex_back_bent_row',
            position: 3,
            muscleGroup: 'back',
            resistanceType: 'weight',
            resistanceValue: 30,
            repsMin: 12,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_h1_4',
            exerciseId: 'ex_legs_goblet_squat',
            position: 4,
            muscleGroup: 'legs',
            resistanceType: 'weight',
            resistanceValue: 25,
            repsMin: 12,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_h1_5',
            exerciseId: 'ex_core_russian_twist',
            position: 5,
            muscleGroup: 'core',
            resistanceType: 'weight',
            resistanceValue: 15,
            repsMin: 15,
            repsMax: 20,
            sets: 2,
          },
        ],
      },
      {
        id: 'block_h2',
        blockNumber: 2,
        name: 'Block 2 - Power',
        exercises: [
          {
            id: 'te_h2_1',
            exerciseId: 'ex_cardio_rower',
            position: 1,
            muscleGroup: 'cardio',
            resistanceType: 'bodyweight',
            resistanceValue: 0,
            repsMin: 0,
            repsMax: 0,
            sets: 1,
            cardioDuration: 120,
            cardioIntensity: 8,
          },
          {
            id: 'te_h2_2',
            exerciseId: 'ex_chest_db_press',
            position: 2,
            muscleGroup: 'chest',
            resistanceType: 'weight',
            resistanceValue: 30,
            repsMin: 12,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_h2_3',
            exerciseId: 'ex_back_lat_pulldown',
            position: 3,
            muscleGroup: 'back',
            resistanceType: 'weight',
            resistanceValue: 35,
            repsMin: 12,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_h2_4',
            exerciseId: 'ex_legs_lunges',
            position: 4,
            muscleGroup: 'legs',
            resistanceType: 'weight',
            resistanceValue: 20,
            repsMin: 12,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_h2_5',
            exerciseId: 'ex_core_plank',
            position: 5,
            muscleGroup: 'core',
            resistanceType: 'bodyweight',
            resistanceValue: 0,
            repsMin: 0,
            repsMax: 0,
            sets: 2,
            cardioDuration: 45,
            cardioIntensity: 7,
          },
        ],
      },
      {
        id: 'block_h3',
        blockNumber: 3,
        name: 'Block 3 - Finisher',
        exercises: [
          {
            id: 'te_h3_1',
            exerciseId: 'ex_cardio_bike',
            position: 1,
            muscleGroup: 'cardio',
            resistanceType: 'bodyweight',
            resistanceValue: 0,
            repsMin: 0,
            repsMax: 0,
            sets: 1,
            cardioDuration: 120,
            cardioIntensity: 9,
          },
          {
            id: 'te_h3_2',
            exerciseId: 'ex_shoulders_lateral_raise',
            position: 2,
            muscleGroup: 'shoulders',
            resistanceType: 'weight',
            resistanceValue: 10,
            repsMin: 12,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_h3_3',
            exerciseId: 'ex_biceps_curl',
            position: 3,
            muscleGroup: 'biceps',
            resistanceType: 'weight',
            resistanceValue: 15,
            repsMin: 12,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_h3_4',
            exerciseId: 'ex_triceps_extension',
            position: 4,
            muscleGroup: 'triceps',
            resistanceType: 'weight',
            resistanceValue: 12,
            repsMin: 12,
            repsMax: 15,
            sets: 2,
          },
          {
            id: 'te_h3_5',
            exerciseId: 'ex_stretch_quad',
            position: 5,
            muscleGroup: 'stretch',
            resistanceType: 'bodyweight',
            resistanceValue: 0,
            repsMin: 0,
            repsMax: 0,
            sets: 1,
            cardioDuration: 30,
            cardioIntensity: 2,
          },
        ],
      },
    ],
    createdAt: '2025-10-12T11:00:00Z',
    updatedAt: '2025-10-20T09:15:00Z',
  },
];

// Helper function to get template by ID
export function getTemplateById(id: string): WorkoutTemplate | undefined {
  return MOCK_TEMPLATES.find(template => template.id === id);
}

// Helper function to get templates by type
export function getTemplatesByType(type: string): WorkoutTemplate[] {
  return MOCK_TEMPLATES.filter(template => template.type === type);
}
