/**
 * Exercise Name Mapping System
 *
 * This file provides manual overrides for exercise names and categories
 * when the auto-detection from folder names is incorrect.
 */

import { MuscleGroup, ExerciseLevel } from './types'

export interface ExerciseOverride {
  name?: string
  category?: MuscleGroup
  equipment?: string
  level?: ExerciseLevel
  instructions?: string[]
  modifications?: string[]
  commonMistakes?: string[]
}

/**
 * Manual overrides for specific exercises
 * Key: Supabase folder name (exerciseId)
 * Value: Override data
 */
export const EXERCISE_NAME_OVERRIDES: Record<string, ExerciseOverride> = {
  // Example overrides - add more as needed
  'one-arm-kettlebell-military-press-to-the-side': {
    name: 'One Arm Kettlebell Military Press',
    category: 'shoulders',
    equipment: 'Kettlebell',
    level: 'advanced',
  },
  // Add more overrides here as you review the exercises
}

/**
 * Get the display name for an exercise
 * Checks overrides first, then falls back to auto-generated name
 */
export function getExerciseName(folderName: string, autoGeneratedName: string): string {
  return EXERCISE_NAME_OVERRIDES[folderName]?.name || autoGeneratedName
}

/**
 * Get the category for an exercise
 * Checks overrides first, then falls back to auto-detected category
 */
export function getExerciseCategory(folderName: string, autoDetectedCategory: MuscleGroup): MuscleGroup {
  return EXERCISE_NAME_OVERRIDES[folderName]?.category || autoDetectedCategory
}

/**
 * Get the equipment for an exercise
 * Checks overrides first, then falls back to auto-detected equipment
 */
export function getExerciseEquipment(folderName: string, autoDetectedEquipment?: string): string | undefined {
  return EXERCISE_NAME_OVERRIDES[folderName]?.equipment || autoDetectedEquipment
}

/**
 * Get the level for an exercise
 * Checks overrides first, then falls back to default level
 */
export function getExerciseLevel(folderName: string, defaultLevel: ExerciseLevel = 'intermediate'): ExerciseLevel {
  return EXERCISE_NAME_OVERRIDES[folderName]?.level || defaultLevel
}

/**
 * Get complete override data for an exercise
 */
export function getExerciseOverride(folderName: string): ExerciseOverride | undefined {
  return EXERCISE_NAME_OVERRIDES[folderName]
}

/**
 * Apply overrides to an exercise object
 */
export function applyExerciseOverrides<T extends { exerciseId: string }>(
  exercise: T,
  override?: ExerciseOverride
): T {
  if (!override) return exercise

  return {
    ...exercise,
    ...(override.name && { name: override.name }),
    ...(override.category && { category: override.category }),
    ...(override.equipment && { equipment: override.equipment }),
    ...(override.level && { level: override.level }),
    ...(override.instructions && { instructions: override.instructions }),
    ...(override.modifications && { modifications: override.modifications }),
    ...(override.commonMistakes && { commonMistakes: override.commonMistakes }),
  }
}

/**
 * Category display names (12 categories)
 */
export const CATEGORY_DISPLAY_NAMES: Record<MuscleGroup, string> = {
  cardio: 'Cardio',
  chest: 'Chest',
  back: 'Back',
  legs: 'Legs',
  core: 'Core',
  shoulders: 'Shoulders',
  biceps: 'Biceps',
  triceps: 'Triceps',
  full_body: 'Full Body',
  stretch: 'Stretch & Mobility',
  forearms: 'Forearms',
  neck: 'Neck',
}

/**
 * Get exercises that need manual review
 * (These don't have overrides and may need category/name corrections)
 */
export function getExercisesNeedingReview(allFolderNames: string[]): string[] {
  return allFolderNames.filter(name => !EXERCISE_NAME_OVERRIDES[name])
}
